##################################################
# Author:       Karn Watcharasupat
# Created:      23 Sep 2022
# Last Updated: 23 Sep 2022
#
# Music Informatics Group
# Center for Music Technology
# Georgia Institute of Technology
##################################################

instrument:
  bcl: Bb Clarinet 
  tru: Trumpet
  tsa: Tenor Saxophone 
  flu: Flute 
  axs: Alto Saxophone 
  asx: Alto Saxophone
  frh: French Horn 
  obo: Oboe 
  sna: Snare Drum 
  xyl: Xylophone 
  tim: Timpani

percussion instruments: [Snare Drum, Xylophone, Timpani]

segment:
  lyricalEtude: Lyrical Etude
  technicalEtude: Technical Etude
  scalesChromatic: Chromatic Scale
  chromaticScale: Chromatic Scale
  scale: Major Scales
  scalesMajor: Major Scales
  sightReading: Sight-Reading
  malletEtude: Mallet Etude
  snareEtude: Snare Etude
  timpaniEtude: Timpani Etude
  readingMallet: Reading-Mallet
  readingSnare: Reading-Snare

columns:
  instrument name(str): Instrument
  activity name(str): ScoreGroup
  start_time(sec): Start
  duration(sec): Duration
