##################################################
# Author:       Karn Watcharasupat
# Created:      15 Sep 2022
# Last Updated: 21 Sep 2022
#
# Music Informatics Group
# Center for Music Technology
# Georgia Institute of Technology
##################################################


instrument:
  EbClarinet: Eb Clarinet

# columns: <year>: <band>: <oldname>: <newname>
columns:
  2013:
    concert:
      CategoryGroup: ScoreGroup
      Category: Description
    middle:
      CategoryGroup: ScoreGroup
      Category: Description
    symphonic:
      CategoryGroup: ScoreGroup
      Category: Description

# assessments:
# - OldScoreGroup: <old score group name, required>
#   OldDescription: <old description name, optional if affecting entire score group>
#   NewScoreGroup: <new score group name, optional if unchanged>
#   NewDescription: <new description name, optional if unchanged>
#   Affects:
#   - Year: <year of band affected>
#     BandLevel:
#     - <level of band affected in that year>
#   Reason: <reason for change>
#
# Type of assessment score name change
# - Variant : Changing variations and/or typos of obviously the same term for standardization
# - Regroup : The score has been moved to another score group
# - Similar : Very similar, but not guaranteed to be the same, scores to be merged
# - Legacy  : These scores that are no longer in use in subsequent years.
#
# CHANGES WILL BE PROCESSED IN THE ORDER IT APPEARS BELOW!

assessments:
  # legacy scores
  ## timpani
  - OldScoreGroup: Reading-Timpani
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [middle, symphonic]
    Reason: Legacy

  ## scales
  - OldScoreGroup: Scales
    OldDescription: Articulation & Style
    Affects:
      - Year: 2013
        BandLevel: [middle]
      - Year: 2014
        BandLevel: [middle]
    Reason: Legacy

  - OldScoreGroup: Scales
    OldDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Scales
    OldDescription: Note Accuracy/Consistency
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Scales
    OldDescription: Note Accuracy
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Scales
    OldDescription: Musicality, Phrasing & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Scales
    OldDescription: Tempo & Consistency
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Scales
    OldDescription: Tone Quality
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Major Scales
    OldDescription: Note Accuracy
    Affects:
      - Year: 2014
        BandLevel: [middle]
    Reason: Legacy

  - OldScoreGroup: Major Scales
    OldDescription: Musicality, Phrasing & Style
    Affects:
      - Year: 2014
        BandLevel: [middle]
    Reason: Legacy

  - OldScoreGroup: Major Scales
    OldDescription: Tempo & Consistency
    Affects:
      - Year: 2014
        BandLevel: [middle]
    Reason: Legacy

  ## artistry/articulation
  - OldScoreGroup: Lyrical Etude
    OldDescription: Artistry
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Sight-Reading
    OldDescription: Artistry
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Legacy

  - OldScoreGroup: Technical Etude
    OldDescription: Artistry
    Affects:
      - Year: 2013
        BandLevel: [concert, symphonic]
      - Year: 2014
        BandLevel: [concert, symphonic]
    Reason: Legacy

  - OldScoreGroup: Technical Etude
    OldDescription: Articulation
    Affects:
      - Year: 2013
        BandLevel: [middle]
      - Year: 2014
        BandLevel: [middle]
    Reason: Legacy

  # chromatic scale
  - OldScoreGroup: Chromatic Scale
    OldDescription: Chromatic
    NewDescription: Chromatic Scale
    Affects:
      - Year: 2014
        BandLevel: [middle]
    Reason: Variant

  - OldScoreGroup: Scales
    OldDescription: Chromatic
    NewScoreGroup: Chromatic Scale
    NewDescription: Chromatic Scale
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, symphonic]
    Reason: Regroup

  # musicality, tempo, & style spellings

  - OldScoreGroup: Lyrical Etude
    OldDescription: Musicallity, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
      - Year: 2015
        BandLevel: [concert, middle, symphonic]
      - Year: 2016
        BandLevel: [concert, middle, symphonic]
      - Year: 2017
        BandLevel: [concert, middle, symphonic]
      - Year: 2018
        BandLevel: [concert, middle, symphonic]
    Reason: Variant
  
  - OldScoreGroup: Sight-Reading
    OldDescription: Musicallity, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
      - Year: 2015
        BandLevel: [concert, middle, symphonic]
      - Year: 2016
        BandLevel: [concert, middle, symphonic]
      - Year: 2017
        BandLevel: [concert, middle, symphonic]
      - Year: 2018
        BandLevel: [concert, middle, symphonic]
    Reason: Variant

  - OldScoreGroup: Technical Etude
    OldDescription: Musicality, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2015
        BandLevel: [middle]
      - Year: 2016
        BandLevel: [middle]
      - Year: 2017
        BandLevel: [middle]
      - Year: 2018
        BandLevel: [middle]
    Reason: Variant

  - OldScoreGroup: Technical Etude
    OldDescription: Musicallity, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
      - Year: 2015
        BandLevel: [concert, symphonic]
      - Year: 2016
        BandLevel: [concert, symphonic]
      - Year: 2017
        BandLevel: [concert, symphonic]
      - Year: 2018
        BandLevel: [concert, symphonic]
    Reason: Variant

  - OldScoreGroup: Mallet Etude
    OldDescription: Musicality, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
      - Year: 2015
        BandLevel: [concert, symphonic]
      - Year: 2016
        BandLevel: [concert, symphonic]
      - Year: 2017
        BandLevel: [concert, symphonic]
      - Year: 2018
        BandLevel: [concert, symphonic]
    Reason: Variant

  - OldScoreGroup: Reading-Mallet
    OldDescription: Musicality & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
      - Year: 2015
        BandLevel: [symphonic]
      - Year: 2016
        BandLevel: [symphonic]
      - Year: 2017
        BandLevel: [symphonic]
      - Year: 2018
        BandLevel: [symphonic]
    Reason: Similar

  - OldScoreGroup: Reading-Mallet
    OldDescription: Musicality,Tempo, & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2015
        BandLevel:
          - concert
      - Year: 2016
        BandLevel:
          - concert
      - Year: 2017
        BandLevel:
          - concert
      - Year: 2018
        BandLevel:
          - concert
    Reason: Variant

  - OldScoreGroup: Reading-Mallet
    OldDescription: Musicality, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2015
        BandLevel: [middle]
      - Year: 2016
        BandLevel: [middle]
      - Year: 2017
        BandLevel: [middle]
      - Year: 2018
        BandLevel: [middle]
    Reason: Variant

  - OldScoreGroup: Snare Etude
    OldDescription: Musicallyty, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Variant

  - OldScoreGroup: Snare Etude
    OldDescription: Musicality, Tempo & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2015
        BandLevel: [concert, symphonic]
      - Year: 2016
        BandLevel: [concert, symphonic]

      - Year: 2017
        BandLevel: [concert, symphonic]

      - Year: 2018
        BandLevel: [concert, symphonic]
    Reason: Variant

  - OldScoreGroup: Reading-Snare
    OldDescription: Musicality & Style
    NewDescription: Musicality, Tempo, & Style
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
      - Year: 2015
        BandLevel: [symphonic]
      - Year: 2016
        BandLevel: [symphonic]
      - Year: 2017
        BandLevel: [symphonic]
      - Year: 2018
        BandLevel: [symphonic]
    Reason: Similar

  # percussion-specific

  - OldScoreGroup: Mallet Etude
    OldDescription: Note Accuracy
    NewDescription: Note Accuracy & Tone
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Similar

  - OldScoreGroup: Timpani Etude
    OldDescription: Note Accuracy
    NewDescription: Tuning Accuracy
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Similar

  - OldScoreGroup: Snare Etude
    OldDescription: Note Accuracy
    NewDescription: Rudimental Accuracy
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Similar

  - OldScoreGroup: Reading-Mallet
    OldDescription: Rhythmic Accuracy
    NewDescription: Rhythmic Accuracy & Articulation
    Affects:
      - Year: 2015
        BandLevel: [middle]
      - Year: 2016
        BandLevel: [concert, middle, symphonic]
      - Year: 2017
        BandLevel: [concert, middle, symphonic]
      - Year: 2018
        BandLevel: [concert, middle, symphonic]
    Reason: Similar

  - OldScoreGroup: Reading-Snare
    OldDescription: Rhythmic Accuracy
    NewDescription: Rhythmic Accuracy & Articulation
    Affects:
      - Year: 2015
        BandLevel: [middle]
      - Year: 2016
        BandLevel: [concert, middle, symphonic]
      - Year: 2017
        BandLevel: [concert, middle, symphonic]
      - Year: 2018
        BandLevel: [concert, middle, symphonic]
    Reason: Similar

  # major scales
  - OldScoreGroup: Scales
    NewScoreGroup: Major Scales
    Affects:
      - Year: 2013
        BandLevel: [concert, middle, symphonic]
      - Year: 2014
        BandLevel: [concert, middle, symphonic]
    Reason: Regroup
