##################################################
# Author:       Karn Watcharasupat
# Created:      15 Sep 2022
# Last Updated: 21 Sep 2022
#
# Music Informatics Group
# Center for Music Technology
# Georgia Institute of Technology
##################################################

missing:
  - Conditions: 
      Year: [2015]
      BandLevel: [concert, symphonic]
      ScoreGroup: [Reading-Snare]
      Description: [Rhythmic Accuracy & Articulation]
    ReplaceWith:
      Description: Rhythmic Accuracy

  #WONTFIX: 2018 has no max score data
  
  - Conditions:
      Year: [2018]
      BandLevel: [middle]
      ScoreGroup: [Lyrical Etude]
      Description: ["Musicality, Tempo & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicallity, Tempo & Style
  
  - Conditions:
      Year: [2018]
      BandLevel: [middle]
      ScoreGroup: [Mallet Etude]
      Description: ["Musicality, Tempo. & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicallity, Tempo & Style

  - Conditions:
      Year: [2018]
      BandLevel: [middle]
      ScoreGroup: [Reading-Mallet]
      Description: ["Musicality, Tempo, & Style", "Musicality,Tempo, & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicality, Tempo & Style

  - Conditions:
      Year: [2018]
      BandLevel: [middle]
      ScoreGroup: [Snare Etude]
      Description: ["Musicality, Tempo, & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicality, Tempo & Style

  - Conditions:
      Year: [2018]
      BandLevel: [middle]
      ScoreGroup: [Technical Etude]
      Description: ["Musicality, Tempo & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicallity, Tempo & Style

  - Conditions:
      Year: [2018]
      BandLevel: [symphonic]
      ScoreGroup: [Mallet Etude]
      Description: ["Musicality & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicality, Tempo & Style

  - Conditions:
      Year: [2018]
      BandLevel: [symphonic]
      ScoreGroup: [Reading-Mallet]
      Description: ["Musicality, Tempo, & Style", "Musicality & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicality, Tempo & Style

  - Conditions:
      Year: [2018]
      BandLevel: [symphonic]
      ScoreGroup: [Reading-Snare]
      Description: ["Musicality & Style"]
    ReplaceWith:
      Year: 2017
      Description: Musicality, Tempo, & Style
    
  
  - Conditions:
      Year: [2018] 
    ReplaceWith:
      Year: 2017